package f_exception;
import java.io.IOException;

class Test{
	public static void main( String [] args ) {   
		try{
			System.exit(0);
		} finally {
			System.out.println("FINALLY");
		} 
	}
}